apiVersion: v1
kind: Service
metadata:
  name: scaleway-finops-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scaleway-finops-exporter
  ports:
    - name: http-metrics
      port: 10056
      targetPort: http-metrics
      protocol: TCP
